### ISSUE TITLE
ConcurrentModificationException when aborting download

### ISSUE THREAD

**Issue by jonmuell** [openHPI/android-app#18]
***Merge Request #13 only***

App crashes under certain circumstances when aborting the download of a video.

**How to reproduce:**

- Download a video
- As soon as the download starts download any other video
- Wait for all downloads to start and then abort the download of the video you started in step 1

**Stacktrace:**

```
java.util.ConcurrentModificationException
            at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
            at de.xikolo.model.DownloadModel.cancelDownload(DownloadModel.java:93)
            at de.xikolo.controller.module.helper.DownloadViewController$2.onClick(DownloadViewController.java:119)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prin53** [comment]
I pushed some changes in request, please review them
